{
  "formatVersion": "1.1",
  "component": {
    "group": "Plugins",
    "module": "dupres",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dupres-unspecified.jar",
          "url": "dupres-unspecified.jar",
          "size": 17785,
          "sha512": "cf51694df21a06a8a2f16716b0796a484f1dd399c4a9a15e99d0d279e40a79d642366d462bf99211e2e8343607983f23713c336cf087421d91e448fcd795fb09",
          "sha256": "45820b12b265e46aad482a47789485c1b9700f0690105e88a77005b58910e251",
          "sha1": "1468bb77e6b95b51829258f93e0ef696d6e06515",
          "md5": "feeff26049378943fe9cc4be7b2b9852"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gradle",
              "type": "jar",
              "extension": "jar",
              "classifier": "sources"
            }
          }
        },
        {
          "group": "pink.madis.apk.arsc",
          "module": "android-chunk-utils",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "dupres-unspecified.jar",
          "url": "dupres-unspecified.jar",
          "size": 17785,
          "sha512": "cf51694df21a06a8a2f16716b0796a484f1dd399c4a9a15e99d0d279e40a79d642366d462bf99211e2e8343607983f23713c336cf087421d91e448fcd795fb09",
          "sha256": "45820b12b265e46aad482a47789485c1b9700f0690105e88a77005b58910e251",
          "sha1": "1468bb77e6b95b51829258f93e0ef696d6e06515",
          "md5": "feeff26049378943fe9cc4be7b2b9852"
        }
      ]
    }
  ]
}
